### ISSUE TITLE
Adding a last slide for introducing indirect association

### ISSUE THREAD

**Issue by thierrychau** [DPI-WE/sdf-record-keeping#1]
@heratyian would it be helpful to add a last slide to sort of start introducing the concept of indirect associations?

<img width="1680" alt="movie-db-6" src="https://github.com/DPI-WE/sdf-record-keeping/assets/100433760/ff463cfc-7a72-4fbb-bfb9-da364771d476">

**Comment by heratyian** [comment]
I like that. Want to add that slide and make a pull request? @thierrychau
